### ISSUE TITLE
Randomisation bug

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt-contrib-matching#134]
### Subject of the issue/enhancement/features
With `_isRandom:true` the zero-indexed item in each option is not restored correctly.

The issue is with the following line: https://github.com/adaptlearning/adapt-contrib-matching/blob/master/js/matchingView.js#L49 evaluating to `null` in the presence of `_index:0`

An example fix could be to change it to:
`value: _.isFinite(selectedOption?._index) ? selectedOption._index : null`

**Comment by oliverfoster** [comment]
Have added bug label and added issue to project board.
