### ISSUE TITLE
Blur event not called

### ISSUE THREAD

**Issue by illuminate-tcaffelle** [adaptlearning/adapt-contrib-matching#136]
When leaving the dropdown list, the blur even isn't being called. I was able to work around it by adding an additional event call after clicking the list item. Added to the `this.$list.on` even located on line 43 of the `dropdown.js` document.

Best guess is the original click even isn't firing changing the close property right and is creating a constant loop of setting the state to false and then back to true. 

If anything, my solution is more of a fallback to ensure that the option is selected and the dropdown goes away as to not prevent progression.

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-matching/blob/b93cd1ff23198210bdb6332d0e232553df87e4f6/js/dropdown.js#L43

What did you add? Which line is the close property?

**Comment by illuminate-tcaffelle** [comment]
Hey Oliver. I added to the event listener on that line that you shared. 
`this.$list.on({
      blur: this.onListBlur,
      click: this.onListBlur
    });`

Since it looks like the onListBlur function controls the needed the show/hide process, I just called that function as well. 

I am using vanilla course with some additional plugins. I can share those as well in case they are interfering. 

The device is a Windows 10 OS.

Let me know if you have any questions.

**Comment by illuminate-tcaffelle** [comment]
Chrome.

What happened was I was testing a series of questions and when I would get to the question that had the dropdowns, I would open the dropdown but it would not close after selecting an option or leaving focus. Even when clicking the arrow on the right that opened the drop down originally. 

To find it, I opened up the JS file and found the function that would start the closing process. I believe it to be the onListBlur  from the comments, but may be mistake. I set a break on the event call and it would not trigger when the criteria was met. 

I added the second event trigger to happen on a click as a failsafe in case there is an issue with the machine/browser not calling the blur event for any other reason.

**Comment by oliverfoster** [comment]
Can you replicate the issue every time? Or is it inconsistent in its appearance? I think I may have seen it once but could never reproduce.

**Comment by illuminate-tcaffelle** [comment]
I have been able to reproduce it and it is consistent. I even deleted and rebuilt the course just in case it was a build error. 

I also just ran it through Firefox with the same results in case it was a browser issue. 

I did notice that when I did try to recreate, the dropdown arrow on the right is working now but the blur event still isn't being triggered.

**Comment by oliverfoster** [comment]
![dropdown](https://user-images.githubusercontent.com/7974663/135109425-1d48cfdc-5594-433a-bbd5-890d75678720.gif)

Would you be able to use something like [screentogif](https://www.screentogif.com/) or similar to record it? and send me a copy of the course? (A zip of everything but the node_modules and build folder is fine).

**Comment by illuminate-tcaffelle** [comment]
Hey Oliver,
Here is a screencap.

![Animation](https://user-images.githubusercontent.com/26385707/135116797-ed431f52-f4c4-4f4c-a97d-4ae59ce8a717.gif)

This is without my particular fix that I mentioned. It's commented above. 

I'm not sure I can share the whole package with you as it does contain proprietary information content wise. What I can do is try and make a new project with just the dropdown question and send it with the same extensions, settings, etc. if you think that will work. If not, I can see what else I can do.

**Comment by oliverfoster** [comment]
You haven't break pointed the `onListBlur` callback function, but the event handler attachment. That is only executed once when the dropdown is created.

**Comment by illuminate-tcaffelle** [comment]
Got it! Thanks for your help and explanation. I'll keep digging and if it's a problem with the extension, let the developer know!
