### ISSUE TITLE
Dropdown select fails on reset (when using tutor)

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [adaptlearning/adapt-contrib-matching#137]
There appears to be a bug with matching when notifications are stacked up and then closed. This is currently not the behaviour of tutor, but for any extensions that expand on the Adapt.notify stack it may cause issues.

Replication of bug can be achieved by using the hack outlined below:
1. Make a change to tutor that forces multiple popups (i.e. add another `notify.create(this.notifyOptions);` below the original on line https://github.com/adaptlearning/adapt-contrib-tutor/blob/master/js/TutorNotify.js#L26, to force the same popup twice)
2. Create a course using matching and an assessment with this altered tutor
3. The first dropdown selection and submission gives assessment feedback and tutor feedback (if configured)
4. Reset the assessment
5. Dropdown options appear on click, but options do not disappear (on click/blur/escape etc)

On console debugging, I can see that the blur event is not been fired on the list items at all. Not sure why the page loses this.

Use `monitorEvents($('.js-dropdown-list')[0], "control")` in the console to confirm difference in before and after reset behaviour.

NB: Functionality is intact when tutor is removed

**Comment by oliverfoster** [comment]
Can't replicate on the latest core, assessment and matching. I'm going to need to know which versions of everything you're using.

![matching-blur1](https://user-images.githubusercontent.com/7974663/139688038-3c8543ec-d788-47a6-b3fc-c9c992aaa849.gif)

![image](https://user-images.githubusercontent.com/7974663/139687682-a3a4e74a-70f7-4c59-ba79-702b55170ca3.png)

**Comment by cahirodoherty-learningpool** [comment]
Apologies, there was a custom plugin hanging around in the configuration that is causing the problem. I'll close this issue now.

**Comment by oliverfoster** [comment]
No worries mate, thanks for checking.

**Comment by cahirodoherty-learningpool** [comment]
@oliverfoster I have updated the ticket details following my investigation and our discussion. The issue is possibly stemming from something in the Core > Notify handling or the a11y work related to that, but it directly affects matching.

**Comment by oliverfoster** [comment]
Just before I forget, you'd mentioned last week that when two notifies are shown, the dropdown stops responding to blur events.

**Comment by cahirodoherty-learningpool** [comment]
> Just before I forget, you'd mentioned last week that when two notifies are shown, the dropdown stops responding to blur events.

Yeah I have updated the description above to show this in the replication steps
