### ISSUE TITLE
matching-item__select-container style is missed

### ISSUE THREAD

**Issue by clara-am** [adaptlearning/adapt-contrib-matching#143]
With the last version, it was missed the style in the check icons problably because someone changed class naming.
Previosly the class was named 
matching__select-state{
    position: absolute;
    top: 50%;
    right: 1rem;
    transform: translateY(-50%);
}
It could be now:
.matching-item {

  &__select-container {
    position: relative;
  }

  &__select-state {
    position: absolute;
    top: 15%;
    right: 1rem;
    transform: translateY(50%);
  }
...

**Comment by guywillis** [comment]
Hi @clara-am,

I believe [v6.0.0](https://github.com/adaptlearning/adapt-contrib-vanilla/releases/tag/v6.0.0) of the Vanilla theme should contain the associated naming amends for the `.matching__select-state` to `.matching-item__select-state` change. 

I would recommend updating your version of the Vanilla theme to see if the issue persists.

**Comment by oliverfoster** [comment]
closed as stale and answered
