### ISSUE TITLE
Change _shouldShowMarking for _canShowMarking in matching.jsx

### ISSUE THREAD

**Issue by clara-am** [adaptlearning/adapt-contrib-matching#169]
### Subject of the issue/enhancement/features
Change _shouldShowMarking for _canShowMarking in matching.jsx template.
Now it looks like undefined and avoid to show the tick/cross next to the item.

### Expected behaviour
True/false from config.

### Actual behaviour
undefined

**Comment by swashbuck** [comment]
Hi, @clara-am . This marking icons seem to be working as expected when setting `_canShowMarking` to either 'true' or 'false.' Where are you seeing 'undefined'? When I use the [React Developer Tools](https://react.dev/learn/react-developer-tools), the value looks to be correctly set.

To clarify, the different between the two properties is:
- `_canShowMarking` is configurable via the course's JSON. This determines if the _intention_ is to show the marking icons after the question has been submitted.
- `shouldShowMarking`, on the other hand, is not configurable and is based on a combination of `isInteractive()`, the `_canShowMarking` configuration, and `_isInteractionComplete` (ex. if the question has been submitted). You can see how it's determined [here](https://github.com/adaptlearning/adapt-contrib-core/blob/d0eaf443becfcdd80dab481d6b03128183f5f319/js/models/questionModel.js#L411):

```
/** @type {boolean} */
get shouldShowMarking() {
  return (!this.isInteractive() && this.get('_canShowMarking') && this.get('_isInteractionComplete'));
}
```
Let me know if this is still not working for you, and I can take another look.

Thanks.

Brad
