### ISSUE TITLE
Tabbing: After pressing 'Reset' the focus shifts several components ahead

### ISSUE THREAD

**Issue by kineoluke** [adaptlearning/adapt-contrib-matching#34]
E.g. I was testing on co-20.

I answered the question incorrectly and pressed 'Reset' via tabbing. After closing the feedback panel the tab focus had shifted to the 'Slider type component' Submit button below. 

@kirsty-hames

**Comment by zenduo** [comment]
Moved to https://adaptlearning.atlassian.net/browse/ABU-479
