### ISSUE TITLE
ie8/9 Disabled State default styling cannot be overriden

### ISSUE THREAD

**Issue by salali** [adaptlearning/adapt-contrib-matching#46]
Having issues where the select text turns into a light grey when disabled on IE8/9. After some research it looks like it's not possible to change that grey. This is causing issues where the text is very hard to read depending on the background colour of the select. Only way around it atm is for it to be styled with a white background colour on the browsers affected.

**Comment by hrajotia** [comment]
@salali - As per discussed with @darylhedley this can't be done without redoing the whole matching component.

**Comment by olivermartinfoster** [comment]
i think sal means that the select boxes should be removed in favour of an html implementation, like: https://select2.github.io/examples.html

**Comment by olivermartinfoster** [comment]
they are much easier to style and the support is damned good

**Comment by moloko** [comment]
select2 does look pretty impressive, any reason we should test this out in
a feature branch?

On 9 January 2015 at 12:00, Oliver Foster <notifications@github.com> wrote:

> i think sal means that the select boxes should be removed in favour of an
> html implementation, like: https://select2.github.io/examples.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adaptlearning/adapt-contrib-matching/issues/46#issuecomment-69325901>
> .
>



-- 
--------------------------------------------------------------------------------------------------------------------------------
IMPORTANT: This email is intended for the use of the individual
addressee(s) named above and may contain information that is confidential,
privileged, or unsuitable for overly sensitive persons with low
self-esteem, no sense of humour, or irrational religious beliefs.
If you have received this email in error, please add some egg whites and
nutmeg, whisk and place in a warm oven for 40 minutes.

**Comment by oliverfoster** [comment]
not for v2 release

**Comment by zenduo** [comment]
@salali going back to your original bug was this resolved? If not are you able to explain with some screenshots the issue and what your desired result would be for IE8 (again with a picture if possible) just to clarify the issue?

**Comment by oliverfoster** [comment]
I can fill you in on Monday. Not sure how available Sal is at the moment for Adapt. He's moved on from Kineo where he was quite instrumental in development for the project.

**Comment by zenduo** [comment]
No problem, speak Monday

**Comment by zenduo** [comment]
Closing as this issue is logged here https://adaptlearning.atlassian.net/browse/ABU-356
