### ISSUE TITLE
_isAtLeastOneCorrectSelection not being reset

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-matching#47]
If you answer a question either partly correct or correct, on subsequent incorrect attempts it will still think you are partly correct due to this attribute not besing reset.

**Comment by zenduo** [comment]
Looks like this one has been closed here? https://github.com/adaptlearning/adapt-contrib-matching/pull/53

**Comment by moloko** [comment]
we were keeping these open just for now until we decide how to QA these issues to make sure they are fixed.
