### ISSUE TITLE
the 'correct' and 'incorrect' classes are not being removed from the items on reset

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-contrib-matching#52]
so you get some weird marking issues going on when the question is set to have more than 1 attempt

should be solved by adding the following to resetQuestion:
```
this.$(".matching-item").removeClass("correct").removeClass("incorrect");
```

**Comment by zenduo** [comment]
Looks like this one has been closed here? https://github.com/adaptlearning/adapt-contrib-matching/pull/53
