### ISSUE TITLE
Small typo in properties.schema

### ISSUE THREAD

**Issue by dennis-learningpool** [adaptlearning/adapt-contrib-matching#59]
In the _items > _options attribute, "Mathing Options" should be "Matching Options":

![image](https://cloud.githubusercontent.com/assets/1692639/7185486/cda874e0-e45a-11e4-8c07-4f8a691bcb73.png)

**Comment by zenduo** [comment]
This is fixed in develop, https://github.com/adaptlearning/adapt-contrib-matching/blob/develop/properties.schema#L49

Closing
